[lib]
proc-macro = true

[features]
salvo = []

[package]
name = "presence-macros"
version = "0.0.0"
edition = "2021"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
